modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "skillcraft"
version = "${version}"
displayName = "Skillcraft"
authors = ["BMJO", "satisfy"]
description = '''
Offering players a new way to progress and unlock new items, blocks, and gear.
With this mod, players will have to level up specific skills to access these rewards, creating a sense of achievement and challenge.
'''
logoFile = "assets/skillcraft/icon.png"

[[dependencies.skillcraft]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skillcraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skillcraft]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"